// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	task "github.com/zjrosen/perles/internal/task"
)

// MockQueryExecutor is an autogenerated mock type for the QueryExecutor type
type MockQueryExecutor struct {
	mock.Mock
}

type MockQueryExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryExecutor) EXPECT() *MockQueryExecutor_Expecter {
	return &MockQueryExecutor_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: query
func (_m *MockQueryExecutor) Execute(query string) ([]task.Issue, error) {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []task.Issue
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]task.Issue, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(string) []task.Issue); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]task.Issue)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQueryExecutor_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockQueryExecutor_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - query string
func (_e *MockQueryExecutor_Expecter) Execute(query interface{}) *MockQueryExecutor_Execute_Call {
	return &MockQueryExecutor_Execute_Call{Call: _e.mock.On("Execute", query)}
}

func (_c *MockQueryExecutor_Execute_Call) Run(run func(query string)) *MockQueryExecutor_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockQueryExecutor_Execute_Call) Return(_a0 []task.Issue, _a1 error) *MockQueryExecutor_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQueryExecutor_Execute_Call) RunAndReturn(run func(string) ([]task.Issue, error)) *MockQueryExecutor_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueryExecutor creates a new instance of MockQueryExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryExecutor {
	mock := &MockQueryExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
