// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	task "github.com/zjrosen/perles/internal/task"
)

// MockBackend is an autogenerated mock type for the Backend type
type MockBackend struct {
	mock.Mock
}

type MockBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackend) EXPECT() *MockBackend_Expecter {
	return &MockBackend_Expecter{mock: &_m.Mock}
}

// CheckCompatibility provides a mock function with no fields
func (_m *MockBackend) CheckCompatibility() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CheckCompatibility")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBackend_CheckCompatibility_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckCompatibility'
type MockBackend_CheckCompatibility_Call struct {
	*mock.Call
}

// CheckCompatibility is a helper method to define mock.On call
func (_e *MockBackend_Expecter) CheckCompatibility() *MockBackend_CheckCompatibility_Call {
	return &MockBackend_CheckCompatibility_Call{Call: _e.mock.On("CheckCompatibility")}
}

func (_c *MockBackend_CheckCompatibility_Call) Run(run func()) *MockBackend_CheckCompatibility_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBackend_CheckCompatibility_Call) Return(_a0 error) *MockBackend_CheckCompatibility_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBackend_CheckCompatibility_Call) RunAndReturn(run func() error) *MockBackend_CheckCompatibility_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *MockBackend) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBackend_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockBackend_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockBackend_Expecter) Close() *MockBackend_Close_Call {
	return &MockBackend_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockBackend_Close_Call) Run(run func()) *MockBackend_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBackend_Close_Call) Return(_a0 error) *MockBackend_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBackend_Close_Call) RunAndReturn(run func() error) *MockBackend_Close_Call {
	_c.Call.Return(run)
	return _c
}

// FlushCaches provides a mock function with given fields: ctx
func (_m *MockBackend) FlushCaches(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FlushCaches")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBackend_FlushCaches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlushCaches'
type MockBackend_FlushCaches_Call struct {
	*mock.Call
}

// FlushCaches is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBackend_Expecter) FlushCaches(ctx interface{}) *MockBackend_FlushCaches_Call {
	return &MockBackend_FlushCaches_Call{Call: _e.mock.On("FlushCaches", ctx)}
}

func (_c *MockBackend_FlushCaches_Call) Run(run func(ctx context.Context)) *MockBackend_FlushCaches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockBackend_FlushCaches_Call) Return(_a0 error) *MockBackend_FlushCaches_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBackend_FlushCaches_Call) RunAndReturn(run func(context.Context) error) *MockBackend_FlushCaches_Call {
	_c.Call.Return(run)
	return _c
}

// Services provides a mock function with no fields
func (_m *MockBackend) Services() task.BackendServices {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Services")
	}

	var r0 task.BackendServices
	if rf, ok := ret.Get(0).(func() task.BackendServices); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(task.BackendServices)
	}

	return r0
}

// MockBackend_Services_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Services'
type MockBackend_Services_Call struct {
	*mock.Call
}

// Services is a helper method to define mock.On call
func (_e *MockBackend_Expecter) Services() *MockBackend_Services_Call {
	return &MockBackend_Services_Call{Call: _e.mock.On("Services")}
}

func (_c *MockBackend_Services_Call) Run(run func()) *MockBackend_Services_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBackend_Services_Call) Return(_a0 task.BackendServices) *MockBackend_Services_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBackend_Services_Call) RunAndReturn(run func() task.BackendServices) *MockBackend_Services_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBackend creates a new instance of MockBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackend {
	mock := &MockBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
