// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	task "github.com/zjrosen/perles/internal/task"
)

// MockTaskExecutor is an autogenerated mock type for the TaskExecutor type
type MockTaskExecutor struct {
	mock.Mock
}

type MockTaskExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskExecutor) EXPECT() *MockTaskExecutor_Expecter {
	return &MockTaskExecutor_Expecter{mock: &_m.Mock}
}

// AddComment provides a mock function with given fields: issueID, author, text
func (_m *MockTaskExecutor) AddComment(issueID string, author string, text string) error {
	ret := _m.Called(issueID, author, text)

	if len(ret) == 0 {
		panic("no return value specified for AddComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(issueID, author, text)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskExecutor_AddComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddComment'
type MockTaskExecutor_AddComment_Call struct {
	*mock.Call
}

// AddComment is a helper method to define mock.On call
//   - issueID string
//   - author string
//   - text string
func (_e *MockTaskExecutor_Expecter) AddComment(issueID interface{}, author interface{}, text interface{}) *MockTaskExecutor_AddComment_Call {
	return &MockTaskExecutor_AddComment_Call{Call: _e.mock.On("AddComment", issueID, author, text)}
}

func (_c *MockTaskExecutor_AddComment_Call) Run(run func(issueID string, author string, text string)) *MockTaskExecutor_AddComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTaskExecutor_AddComment_Call) Return(_a0 error) *MockTaskExecutor_AddComment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskExecutor_AddComment_Call) RunAndReturn(run func(string, string, string) error) *MockTaskExecutor_AddComment_Call {
	_c.Call.Return(run)
	return _c
}

// AddDependency provides a mock function with given fields: taskID, dependsOnID
func (_m *MockTaskExecutor) AddDependency(taskID string, dependsOnID string) error {
	ret := _m.Called(taskID, dependsOnID)

	if len(ret) == 0 {
		panic("no return value specified for AddDependency")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(taskID, dependsOnID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskExecutor_AddDependency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDependency'
type MockTaskExecutor_AddDependency_Call struct {
	*mock.Call
}

// AddDependency is a helper method to define mock.On call
//   - taskID string
//   - dependsOnID string
func (_e *MockTaskExecutor_Expecter) AddDependency(taskID interface{}, dependsOnID interface{}) *MockTaskExecutor_AddDependency_Call {
	return &MockTaskExecutor_AddDependency_Call{Call: _e.mock.On("AddDependency", taskID, dependsOnID)}
}

func (_c *MockTaskExecutor_AddDependency_Call) Run(run func(taskID string, dependsOnID string)) *MockTaskExecutor_AddDependency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockTaskExecutor_AddDependency_Call) Return(_a0 error) *MockTaskExecutor_AddDependency_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskExecutor_AddDependency_Call) RunAndReturn(run func(string, string) error) *MockTaskExecutor_AddDependency_Call {
	_c.Call.Return(run)
	return _c
}

// CloseIssue provides a mock function with given fields: issueID, reason
func (_m *MockTaskExecutor) CloseIssue(issueID string, reason string) error {
	ret := _m.Called(issueID, reason)

	if len(ret) == 0 {
		panic("no return value specified for CloseIssue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(issueID, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskExecutor_CloseIssue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseIssue'
type MockTaskExecutor_CloseIssue_Call struct {
	*mock.Call
}

// CloseIssue is a helper method to define mock.On call
//   - issueID string
//   - reason string
func (_e *MockTaskExecutor_Expecter) CloseIssue(issueID interface{}, reason interface{}) *MockTaskExecutor_CloseIssue_Call {
	return &MockTaskExecutor_CloseIssue_Call{Call: _e.mock.On("CloseIssue", issueID, reason)}
}

func (_c *MockTaskExecutor_CloseIssue_Call) Run(run func(issueID string, reason string)) *MockTaskExecutor_CloseIssue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockTaskExecutor_CloseIssue_Call) Return(_a0 error) *MockTaskExecutor_CloseIssue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskExecutor_CloseIssue_Call) RunAndReturn(run func(string, string) error) *MockTaskExecutor_CloseIssue_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEpic provides a mock function with given fields: title, description, labels
func (_m *MockTaskExecutor) CreateEpic(title string, description string, labels []string) (task.CreateResult, error) {
	ret := _m.Called(title, description, labels)

	if len(ret) == 0 {
		panic("no return value specified for CreateEpic")
	}

	var r0 task.CreateResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, []string) (task.CreateResult, error)); ok {
		return rf(title, description, labels)
	}
	if rf, ok := ret.Get(0).(func(string, string, []string) task.CreateResult); ok {
		r0 = rf(title, description, labels)
	} else {
		r0 = ret.Get(0).(task.CreateResult)
	}

	if rf, ok := ret.Get(1).(func(string, string, []string) error); ok {
		r1 = rf(title, description, labels)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskExecutor_CreateEpic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEpic'
type MockTaskExecutor_CreateEpic_Call struct {
	*mock.Call
}

// CreateEpic is a helper method to define mock.On call
//   - title string
//   - description string
//   - labels []string
func (_e *MockTaskExecutor_Expecter) CreateEpic(title interface{}, description interface{}, labels interface{}) *MockTaskExecutor_CreateEpic_Call {
	return &MockTaskExecutor_CreateEpic_Call{Call: _e.mock.On("CreateEpic", title, description, labels)}
}

func (_c *MockTaskExecutor_CreateEpic_Call) Run(run func(title string, description string, labels []string)) *MockTaskExecutor_CreateEpic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockTaskExecutor_CreateEpic_Call) Return(_a0 task.CreateResult, _a1 error) *MockTaskExecutor_CreateEpic_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskExecutor_CreateEpic_Call) RunAndReturn(run func(string, string, []string) (task.CreateResult, error)) *MockTaskExecutor_CreateEpic_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTask provides a mock function with given fields: title, description, parentID, assignee, labels
func (_m *MockTaskExecutor) CreateTask(title string, description string, parentID string, assignee string, labels []string) (task.CreateResult, error) {
	ret := _m.Called(title, description, parentID, assignee, labels)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 task.CreateResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, []string) (task.CreateResult, error)); ok {
		return rf(title, description, parentID, assignee, labels)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string, []string) task.CreateResult); ok {
		r0 = rf(title, description, parentID, assignee, labels)
	} else {
		r0 = ret.Get(0).(task.CreateResult)
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string, []string) error); ok {
		r1 = rf(title, description, parentID, assignee, labels)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskExecutor_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockTaskExecutor_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - title string
//   - description string
//   - parentID string
//   - assignee string
//   - labels []string
func (_e *MockTaskExecutor_Expecter) CreateTask(title interface{}, description interface{}, parentID interface{}, assignee interface{}, labels interface{}) *MockTaskExecutor_CreateTask_Call {
	return &MockTaskExecutor_CreateTask_Call{Call: _e.mock.On("CreateTask", title, description, parentID, assignee, labels)}
}

func (_c *MockTaskExecutor_CreateTask_Call) Run(run func(title string, description string, parentID string, assignee string, labels []string)) *MockTaskExecutor_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string), args[4].([]string))
	})
	return _c
}

func (_c *MockTaskExecutor_CreateTask_Call) Return(_a0 task.CreateResult, _a1 error) *MockTaskExecutor_CreateTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskExecutor_CreateTask_Call) RunAndReturn(run func(string, string, string, string, []string) (task.CreateResult, error)) *MockTaskExecutor_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteIssues provides a mock function with given fields: issueIDs
func (_m *MockTaskExecutor) DeleteIssues(issueIDs []string) error {
	ret := _m.Called(issueIDs)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIssues")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]string) error); ok {
		r0 = rf(issueIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskExecutor_DeleteIssues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIssues'
type MockTaskExecutor_DeleteIssues_Call struct {
	*mock.Call
}

// DeleteIssues is a helper method to define mock.On call
//   - issueIDs []string
func (_e *MockTaskExecutor_Expecter) DeleteIssues(issueIDs interface{}) *MockTaskExecutor_DeleteIssues_Call {
	return &MockTaskExecutor_DeleteIssues_Call{Call: _e.mock.On("DeleteIssues", issueIDs)}
}

func (_c *MockTaskExecutor_DeleteIssues_Call) Run(run func(issueIDs []string)) *MockTaskExecutor_DeleteIssues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockTaskExecutor_DeleteIssues_Call) Return(_a0 error) *MockTaskExecutor_DeleteIssues_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskExecutor_DeleteIssues_Call) RunAndReturn(run func([]string) error) *MockTaskExecutor_DeleteIssues_Call {
	_c.Call.Return(run)
	return _c
}

// GetComments provides a mock function with given fields: issueID
func (_m *MockTaskExecutor) GetComments(issueID string) ([]task.Comment, error) {
	ret := _m.Called(issueID)

	if len(ret) == 0 {
		panic("no return value specified for GetComments")
	}

	var r0 []task.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]task.Comment, error)); ok {
		return rf(issueID)
	}
	if rf, ok := ret.Get(0).(func(string) []task.Comment); ok {
		r0 = rf(issueID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]task.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(issueID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskExecutor_GetComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComments'
type MockTaskExecutor_GetComments_Call struct {
	*mock.Call
}

// GetComments is a helper method to define mock.On call
//   - issueID string
func (_e *MockTaskExecutor_Expecter) GetComments(issueID interface{}) *MockTaskExecutor_GetComments_Call {
	return &MockTaskExecutor_GetComments_Call{Call: _e.mock.On("GetComments", issueID)}
}

func (_c *MockTaskExecutor_GetComments_Call) Run(run func(issueID string)) *MockTaskExecutor_GetComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTaskExecutor_GetComments_Call) Return(_a0 []task.Comment, _a1 error) *MockTaskExecutor_GetComments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskExecutor_GetComments_Call) RunAndReturn(run func(string) ([]task.Comment, error)) *MockTaskExecutor_GetComments_Call {
	_c.Call.Return(run)
	return _c
}

// ReopenIssue provides a mock function with given fields: issueID
func (_m *MockTaskExecutor) ReopenIssue(issueID string) error {
	ret := _m.Called(issueID)

	if len(ret) == 0 {
		panic("no return value specified for ReopenIssue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(issueID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskExecutor_ReopenIssue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReopenIssue'
type MockTaskExecutor_ReopenIssue_Call struct {
	*mock.Call
}

// ReopenIssue is a helper method to define mock.On call
//   - issueID string
func (_e *MockTaskExecutor_Expecter) ReopenIssue(issueID interface{}) *MockTaskExecutor_ReopenIssue_Call {
	return &MockTaskExecutor_ReopenIssue_Call{Call: _e.mock.On("ReopenIssue", issueID)}
}

func (_c *MockTaskExecutor_ReopenIssue_Call) Run(run func(issueID string)) *MockTaskExecutor_ReopenIssue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTaskExecutor_ReopenIssue_Call) Return(_a0 error) *MockTaskExecutor_ReopenIssue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskExecutor_ReopenIssue_Call) RunAndReturn(run func(string) error) *MockTaskExecutor_ReopenIssue_Call {
	_c.Call.Return(run)
	return _c
}

// SetLabels provides a mock function with given fields: issueID, labels
func (_m *MockTaskExecutor) SetLabels(issueID string, labels []string) error {
	ret := _m.Called(issueID, labels)

	if len(ret) == 0 {
		panic("no return value specified for SetLabels")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []string) error); ok {
		r0 = rf(issueID, labels)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskExecutor_SetLabels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLabels'
type MockTaskExecutor_SetLabels_Call struct {
	*mock.Call
}

// SetLabels is a helper method to define mock.On call
//   - issueID string
//   - labels []string
func (_e *MockTaskExecutor_Expecter) SetLabels(issueID interface{}, labels interface{}) *MockTaskExecutor_SetLabels_Call {
	return &MockTaskExecutor_SetLabels_Call{Call: _e.mock.On("SetLabels", issueID, labels)}
}

func (_c *MockTaskExecutor_SetLabels_Call) Run(run func(issueID string, labels []string)) *MockTaskExecutor_SetLabels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]string))
	})
	return _c
}

func (_c *MockTaskExecutor_SetLabels_Call) Return(_a0 error) *MockTaskExecutor_SetLabels_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskExecutor_SetLabels_Call) RunAndReturn(run func(string, []string) error) *MockTaskExecutor_SetLabels_Call {
	_c.Call.Return(run)
	return _c
}

// ShowIssue provides a mock function with given fields: issueID
func (_m *MockTaskExecutor) ShowIssue(issueID string) (*task.Issue, error) {
	ret := _m.Called(issueID)

	if len(ret) == 0 {
		panic("no return value specified for ShowIssue")
	}

	var r0 *task.Issue
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*task.Issue, error)); ok {
		return rf(issueID)
	}
	if rf, ok := ret.Get(0).(func(string) *task.Issue); ok {
		r0 = rf(issueID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*task.Issue)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(issueID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskExecutor_ShowIssue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowIssue'
type MockTaskExecutor_ShowIssue_Call struct {
	*mock.Call
}

// ShowIssue is a helper method to define mock.On call
//   - issueID string
func (_e *MockTaskExecutor_Expecter) ShowIssue(issueID interface{}) *MockTaskExecutor_ShowIssue_Call {
	return &MockTaskExecutor_ShowIssue_Call{Call: _e.mock.On("ShowIssue", issueID)}
}

func (_c *MockTaskExecutor_ShowIssue_Call) Run(run func(issueID string)) *MockTaskExecutor_ShowIssue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTaskExecutor_ShowIssue_Call) Return(_a0 *task.Issue, _a1 error) *MockTaskExecutor_ShowIssue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskExecutor_ShowIssue_Call) RunAndReturn(run func(string) (*task.Issue, error)) *MockTaskExecutor_ShowIssue_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDescription provides a mock function with given fields: issueID, description
func (_m *MockTaskExecutor) UpdateDescription(issueID string, description string) error {
	ret := _m.Called(issueID, description)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDescription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(issueID, description)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskExecutor_UpdateDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDescription'
type MockTaskExecutor_UpdateDescription_Call struct {
	*mock.Call
}

// UpdateDescription is a helper method to define mock.On call
//   - issueID string
//   - description string
func (_e *MockTaskExecutor_Expecter) UpdateDescription(issueID interface{}, description interface{}) *MockTaskExecutor_UpdateDescription_Call {
	return &MockTaskExecutor_UpdateDescription_Call{Call: _e.mock.On("UpdateDescription", issueID, description)}
}

func (_c *MockTaskExecutor_UpdateDescription_Call) Run(run func(issueID string, description string)) *MockTaskExecutor_UpdateDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockTaskExecutor_UpdateDescription_Call) Return(_a0 error) *MockTaskExecutor_UpdateDescription_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskExecutor_UpdateDescription_Call) RunAndReturn(run func(string, string) error) *MockTaskExecutor_UpdateDescription_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIssue provides a mock function with given fields: issueID, opts
func (_m *MockTaskExecutor) UpdateIssue(issueID string, opts task.UpdateOptions) error {
	ret := _m.Called(issueID, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIssue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, task.UpdateOptions) error); ok {
		r0 = rf(issueID, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskExecutor_UpdateIssue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIssue'
type MockTaskExecutor_UpdateIssue_Call struct {
	*mock.Call
}

// UpdateIssue is a helper method to define mock.On call
//   - issueID string
//   - opts task.UpdateOptions
func (_e *MockTaskExecutor_Expecter) UpdateIssue(issueID interface{}, opts interface{}) *MockTaskExecutor_UpdateIssue_Call {
	return &MockTaskExecutor_UpdateIssue_Call{Call: _e.mock.On("UpdateIssue", issueID, opts)}
}

func (_c *MockTaskExecutor_UpdateIssue_Call) Run(run func(issueID string, opts task.UpdateOptions)) *MockTaskExecutor_UpdateIssue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(task.UpdateOptions))
	})
	return _c
}

func (_c *MockTaskExecutor_UpdateIssue_Call) Return(_a0 error) *MockTaskExecutor_UpdateIssue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskExecutor_UpdateIssue_Call) RunAndReturn(run func(string, task.UpdateOptions) error) *MockTaskExecutor_UpdateIssue_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNotes provides a mock function with given fields: issueID, notes
func (_m *MockTaskExecutor) UpdateNotes(issueID string, notes string) error {
	ret := _m.Called(issueID, notes)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNotes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(issueID, notes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskExecutor_UpdateNotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNotes'
type MockTaskExecutor_UpdateNotes_Call struct {
	*mock.Call
}

// UpdateNotes is a helper method to define mock.On call
//   - issueID string
//   - notes string
func (_e *MockTaskExecutor_Expecter) UpdateNotes(issueID interface{}, notes interface{}) *MockTaskExecutor_UpdateNotes_Call {
	return &MockTaskExecutor_UpdateNotes_Call{Call: _e.mock.On("UpdateNotes", issueID, notes)}
}

func (_c *MockTaskExecutor_UpdateNotes_Call) Run(run func(issueID string, notes string)) *MockTaskExecutor_UpdateNotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockTaskExecutor_UpdateNotes_Call) Return(_a0 error) *MockTaskExecutor_UpdateNotes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskExecutor_UpdateNotes_Call) RunAndReturn(run func(string, string) error) *MockTaskExecutor_UpdateNotes_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePriority provides a mock function with given fields: issueID, priority
func (_m *MockTaskExecutor) UpdatePriority(issueID string, priority task.Priority) error {
	ret := _m.Called(issueID, priority)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePriority")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, task.Priority) error); ok {
		r0 = rf(issueID, priority)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskExecutor_UpdatePriority_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePriority'
type MockTaskExecutor_UpdatePriority_Call struct {
	*mock.Call
}

// UpdatePriority is a helper method to define mock.On call
//   - issueID string
//   - priority task.Priority
func (_e *MockTaskExecutor_Expecter) UpdatePriority(issueID interface{}, priority interface{}) *MockTaskExecutor_UpdatePriority_Call {
	return &MockTaskExecutor_UpdatePriority_Call{Call: _e.mock.On("UpdatePriority", issueID, priority)}
}

func (_c *MockTaskExecutor_UpdatePriority_Call) Run(run func(issueID string, priority task.Priority)) *MockTaskExecutor_UpdatePriority_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(task.Priority))
	})
	return _c
}

func (_c *MockTaskExecutor_UpdatePriority_Call) Return(_a0 error) *MockTaskExecutor_UpdatePriority_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskExecutor_UpdatePriority_Call) RunAndReturn(run func(string, task.Priority) error) *MockTaskExecutor_UpdatePriority_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: issueID, status
func (_m *MockTaskExecutor) UpdateStatus(issueID string, status task.Status) error {
	ret := _m.Called(issueID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, task.Status) error); ok {
		r0 = rf(issueID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskExecutor_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockTaskExecutor_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - issueID string
//   - status task.Status
func (_e *MockTaskExecutor_Expecter) UpdateStatus(issueID interface{}, status interface{}) *MockTaskExecutor_UpdateStatus_Call {
	return &MockTaskExecutor_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", issueID, status)}
}

func (_c *MockTaskExecutor_UpdateStatus_Call) Run(run func(issueID string, status task.Status)) *MockTaskExecutor_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(task.Status))
	})
	return _c
}

func (_c *MockTaskExecutor_UpdateStatus_Call) Return(_a0 error) *MockTaskExecutor_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskExecutor_UpdateStatus_Call) RunAndReturn(run func(string, task.Status) error) *MockTaskExecutor_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTitle provides a mock function with given fields: issueID, title
func (_m *MockTaskExecutor) UpdateTitle(issueID string, title string) error {
	ret := _m.Called(issueID, title)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTitle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(issueID, title)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskExecutor_UpdateTitle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTitle'
type MockTaskExecutor_UpdateTitle_Call struct {
	*mock.Call
}

// UpdateTitle is a helper method to define mock.On call
//   - issueID string
//   - title string
func (_e *MockTaskExecutor_Expecter) UpdateTitle(issueID interface{}, title interface{}) *MockTaskExecutor_UpdateTitle_Call {
	return &MockTaskExecutor_UpdateTitle_Call{Call: _e.mock.On("UpdateTitle", issueID, title)}
}

func (_c *MockTaskExecutor_UpdateTitle_Call) Run(run func(issueID string, title string)) *MockTaskExecutor_UpdateTitle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockTaskExecutor_UpdateTitle_Call) Return(_a0 error) *MockTaskExecutor_UpdateTitle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskExecutor_UpdateTitle_Call) RunAndReturn(run func(string, string) error) *MockTaskExecutor_UpdateTitle_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateType provides a mock function with given fields: issueID, issueType
func (_m *MockTaskExecutor) UpdateType(issueID string, issueType task.IssueType) error {
	ret := _m.Called(issueID, issueType)

	if len(ret) == 0 {
		panic("no return value specified for UpdateType")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, task.IssueType) error); ok {
		r0 = rf(issueID, issueType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskExecutor_UpdateType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateType'
type MockTaskExecutor_UpdateType_Call struct {
	*mock.Call
}

// UpdateType is a helper method to define mock.On call
//   - issueID string
//   - issueType task.IssueType
func (_e *MockTaskExecutor_Expecter) UpdateType(issueID interface{}, issueType interface{}) *MockTaskExecutor_UpdateType_Call {
	return &MockTaskExecutor_UpdateType_Call{Call: _e.mock.On("UpdateType", issueID, issueType)}
}

func (_c *MockTaskExecutor_UpdateType_Call) Run(run func(issueID string, issueType task.IssueType)) *MockTaskExecutor_UpdateType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(task.IssueType))
	})
	return _c
}

func (_c *MockTaskExecutor_UpdateType_Call) Return(_a0 error) *MockTaskExecutor_UpdateType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskExecutor_UpdateType_Call) RunAndReturn(run func(string, task.IssueType) error) *MockTaskExecutor_UpdateType_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskExecutor creates a new instance of MockTaskExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskExecutor {
	mock := &MockTaskExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
