// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockQueryHelpers is an autogenerated mock type for the QueryHelpers type
type MockQueryHelpers struct {
	mock.Mock
}

type MockQueryHelpers_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryHelpers) EXPECT() *MockQueryHelpers_Expecter {
	return &MockQueryHelpers_Expecter{mock: &_m.Mock}
}

// BuildIDQuery provides a mock function with given fields: ids
func (_m *MockQueryHelpers) BuildIDQuery(ids []string) string {
	ret := _m.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for BuildIDQuery")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func([]string) string); ok {
		r0 = rf(ids)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockQueryHelpers_BuildIDQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildIDQuery'
type MockQueryHelpers_BuildIDQuery_Call struct {
	*mock.Call
}

// BuildIDQuery is a helper method to define mock.On call
//   - ids []string
func (_e *MockQueryHelpers_Expecter) BuildIDQuery(ids interface{}) *MockQueryHelpers_BuildIDQuery_Call {
	return &MockQueryHelpers_BuildIDQuery_Call{Call: _e.mock.On("BuildIDQuery", ids)}
}

func (_c *MockQueryHelpers_BuildIDQuery_Call) Run(run func(ids []string)) *MockQueryHelpers_BuildIDQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockQueryHelpers_BuildIDQuery_Call) Return(_a0 string) *MockQueryHelpers_BuildIDQuery_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueryHelpers_BuildIDQuery_Call) RunAndReturn(run func([]string) string) *MockQueryHelpers_BuildIDQuery_Call {
	_c.Call.Return(run)
	return _c
}

// IsStructuredQuery provides a mock function with given fields: input
func (_m *MockQueryHelpers) IsStructuredQuery(input string) bool {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for IsStructuredQuery")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockQueryHelpers_IsStructuredQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsStructuredQuery'
type MockQueryHelpers_IsStructuredQuery_Call struct {
	*mock.Call
}

// IsStructuredQuery is a helper method to define mock.On call
//   - input string
func (_e *MockQueryHelpers_Expecter) IsStructuredQuery(input interface{}) *MockQueryHelpers_IsStructuredQuery_Call {
	return &MockQueryHelpers_IsStructuredQuery_Call{Call: _e.mock.On("IsStructuredQuery", input)}
}

func (_c *MockQueryHelpers_IsStructuredQuery_Call) Run(run func(input string)) *MockQueryHelpers_IsStructuredQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockQueryHelpers_IsStructuredQuery_Call) Return(_a0 bool) *MockQueryHelpers_IsStructuredQuery_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueryHelpers_IsStructuredQuery_Call) RunAndReturn(run func(string) bool) *MockQueryHelpers_IsStructuredQuery_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateQuery provides a mock function with given fields: query
func (_m *MockQueryHelpers) ValidateQuery(query string) error {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for ValidateQuery")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(query)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQueryHelpers_ValidateQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateQuery'
type MockQueryHelpers_ValidateQuery_Call struct {
	*mock.Call
}

// ValidateQuery is a helper method to define mock.On call
//   - query string
func (_e *MockQueryHelpers_Expecter) ValidateQuery(query interface{}) *MockQueryHelpers_ValidateQuery_Call {
	return &MockQueryHelpers_ValidateQuery_Call{Call: _e.mock.On("ValidateQuery", query)}
}

func (_c *MockQueryHelpers_ValidateQuery_Call) Run(run func(query string)) *MockQueryHelpers_ValidateQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockQueryHelpers_ValidateQuery_Call) Return(_a0 error) *MockQueryHelpers_ValidateQuery_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueryHelpers_ValidateQuery_Call) RunAndReturn(run func(string) error) *MockQueryHelpers_ValidateQuery_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueryHelpers creates a new instance of MockQueryHelpers. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryHelpers(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryHelpers {
	mock := &MockQueryHelpers{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
